package com.planagency.goplan.service;
import com.planagency.goplan.dto.ProjectRequestDto;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.util.zip.ZipOutputStream;
import lombok.RequiredArgsConstructor;
import java.util.zip.ZipEntry;
import java.util.Map;
import com.planagency.goplan.enums.Frameworks;
import com.planagency.goplan.startegy.ProjectGeneratorStrategy;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Service
@RequiredArgsConstructor
public class ProjectGeneratorService {

    private final Map<Frameworks, ProjectGeneratorStrategy> strategyMap;
  
    public ProjectGeneratorService(List<ProjectGeneratorStrategy> strategies) {
        this.strategyMap = strategies.stream()
                .collect(Collectors.toMap(ProjectGeneratorStrategy::getSupportedFramework, Function.identity()));
    }

    public byte[] generateProject(ProjectRequestDto request) {
        log.info("Engine routing request for framework: {}", request.framework());

        ProjectGeneratorStrategy strategy = strategyMap.get(request.framework());
        if (strategy == null) {
            throw new IllegalArgumentException("No generator found for framework: " + request.framework());
        }

        try (ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
             ZipOutputStream zipOutputStream = new ZipOutputStream(byteArrayOutputStream)) {

            String baseFolder = request.projectName() + "/";

    
            String readMeContent = generateReadMe(request);
            addFileToZip(zipOutputStream, baseFolder + "README.md", readMeContent);

            strategy.generateProject(zipOutputStream, request);

            zipOutputStream.finish();
            return byteArrayOutputStream.toByteArray();

        } catch (IOException e) {
            log.error("Critical failure during generation", e);
            throw new RuntimeException("Failed to assemble the project ZIP file", e);
        }
    }

    private void addFileToZip(ZipOutputStream zipOutputStream, String filePath, String content) throws IOException {
        ZipEntry entry = new ZipEntry(filePath);
        zipOutputStream.putNextEntry(entry);
        zipOutputStream.write(content.getBytes(StandardCharsets.UTF_8));
        zipOutputStream.closeEntry();
    }

    private String generateReadMe(ProjectRequestDto request) {
        return "# " + request.projectName() + "\nGenerated by GoPlan using " + request.framework();
    }
   
}
